- notebooks/landing-page.md
Add an overview section with motivation, structure, and running instructions
> Add overview section

- .github/workflows/make-comment.yaml
This PR adds an action to make a comment in each newly opened PR giving a link to a preview of the rendered book.
The preview machinery itself is not in this PR, I'm working on it over in #7, but I need this action to be merged first so it can run from main (otherwise it won't run at all and we can't test it).
> Simple action to add a comment with preview link to the PR

- notebooks/example-workflows/moore-oklahoma-tornado.ipynb
- notebooks/foundations/pyart-basics.ipynb
- notebooks/foundations/pyart-corrections.ipynb
- notebooks/foundations/pyart-gridding.ipynb
Remove a few bugs in the notebooks, ensure consistency in referring to Py-ART
> Fix bugs in notebooks

- .github/workflows/build-book.yaml
- .github/workflows/link-checker.yaml
This PR adds scheduled nightly runs of the book-build and link-checker actions.
> Add scheduled builds

- notebooks/example-workflows/moore-oklahoma-tornado.ipynb
- notebooks/landing-page.md
ARM climate research facility needs to be changed to ARM user facility
> Update correct ARM name

- .github/workflows/nightly-build.yaml
This fixes the failing nightly build, changing the path to the configuration files
> Update path to nb in nightly

- _config.yml
> Fix navbar link

- _config.yml
See https://github.com/ProjectPythiaCookbooks/cookbook-template/pull/54 and https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/issues/32 going to test this out with this cookbook first.
> Update _config.yml to use additional keys

- .github/workflows/deploy-book.yaml
- .github/workflows/trigger-book-build.yaml
- _config.yml
> Add ARM username and password to the build book action

- notebooks/example-workflows/cacti-data-quality-example.ipynb
Clean up the last portion of the corrections notebook.
> Clean up last part of corrections workflow

- environment.yml
Update the environment version of Python
> Update environment to 3.9

- _config.yml
Just trying this out... switching notebook execution over to binder.
I expect this will probably fail because I don't think we're currently handling the secrets appropriately.
> Try switching to binderbot

- .github/workflows/trigger-book-build.yaml
> fix yaml syntax

- .github/workflows/trigger-book-build.yaml
> Fix shell script syntax

- environment.yml
Add interactive packages to the environment
> Update environment.yml for interactive

- _config.yml
- notebooks/radar-basics/radar-basics.ipynb
Skip NOAA links in the link checker
> Skip noaa links

- environment.yml
> Pin to Python < 3.12 to fix broken binder

- environment.yml
Include JMA data release for open-radar-data
> FIX: Update env to include open-radar-data with JMA data

- environment.yml
Fix the build for the cookbook by pinning less than numpy 2.0
> FIX: Fix build by using older numpy

- environment.yml
Remove pinning <3.12 for Python
> FIX: Remove python <3.12 pinning
